version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: rasalit-nginx
    volumes:
      - ./rasalit.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/rasalit/html/index.html
    ports:
      - "8000:8000"
    depends_on:
      - rasalit-diet-explorer
      - rasalit-live-nlu
      - rasalit-nlu-cluster
      - rasalit-overview
      - rasalit-spelling
    restart: on-failure

  rasalit-diet-explorer:
    image: ghcr.io/RasaHQ/rasalit-diet-explorer:latest
    volumes:
      - {rasa_project_dir}:/home/appuser
    container_name: rasalit-diet-explorer
    environment:
      - PORT=8500

  rasalit-live-nlu:
    image: ghcr.io/RasaHQ/rasalit-live-nlu:latest
    volumes:
      - {rasa_project_dir}:/home/appuser
    container_name: rasalit-live-nlu
    {depends_on_duckling}
    environment:
      - PORT=8501
      - {duckling_url_env}

  rasalit-nlu-cluster:
    image: ghcr.io/RasaHQ/rasalit-nlu-cluster:latest
    volumes:
      - {rasa_project_dir}:/home/appuser
    container_name: rasalit-nlu-cluster
    environment:
      - PORT=8502

  rasalit-overview:
    image: ghcr.io/RasaHQ/rasalit-overview:latest
    volumes:
      - {rasa_project_dir}:/home/appuser
    container_name: rasalit-overview
    environment:
      - PORT=8503
      - FOLDER={overview_folder}

  rasalit-spelling:
    image: ghcr.io/RasaHQ/rasalit-spelling:latest
    volumes:
      - {rasa_project_dir}:/home/appuser
    container_name: rasalit-spelling
    {depends_on_duckling}
    environment:
      - PORT=8504
      - {duckling_url_env}

{duckling_service}
