version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: rasalit-nginx
    volumes:
      - ./nginx/rasalit.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/var/www/rasalit/html/index.html
    ports:
      - "8000:8000"
    depends_on:
      - rasalit-diet-explorer
      - rasalit-live-nlu
      - rasalit-nlu-cluster
      - rasalit-overview
      - rasalit-spelling
    restart: on-failure

  rasalit-diet-explorer:
    build:
      context: .
      target: rasalit-diet-explorer
    volumes:
      - $RASA_PROJECT_DIR:/home/appuser
    container_name: rasalit-diet-explorer
    environment:
      - PORT=8500

  rasalit-live-nlu:
    build:
      context: .
      target: rasalit-live-nlu
    volumes:
      - $RASA_PROJECT_DIR:/home/appuser
    container_name: rasalit-live-nlu
    depends_on:
      - duckling
    environment:
      - PORT=8501
      - "RASA_DUCKLING_HTTP_URL=http://duckling:8000"

  rasalit-nlu-cluster:
    build:
      context: .
      target: rasalit-nlu-cluster
    volumes:
      - $RASA_PROJECT_DIR:/home/appuser
    container_name: rasalit-nlu-cluster
    environment:
      - PORT=8502

  rasalit-overview:
    build:
      context: .
      target: rasalit-overview
    volumes:
      - $RASA_PROJECT_DIR:/home/appuser
    container_name: rasalit-overview
    environment:
      - PORT=8503
      - FOLDER=${OVERVIEW_FOLDER:-gridresults}

  rasalit-spelling:
    build:
      context: .
      target: rasalit-spelling
    volumes:
      - $RASA_PROJECT_DIR:/home/appuser
    container_name: rasalit-spelling
    depends_on:
      - duckling
    environment:
      - PORT=8504
      - "RASA_DUCKLING_HTTP_URL=http://duckling:8000"

  duckling:
    image: rasa/duckling
    container_name: rasalit-duckling
