import pathlib
import subprocess
import pandas as pd
import click


def app_path(py_file):
    found_path = str(pathlib.Path(__file__).parent.absolute() / py_file)
    assert pathlib.Path(found_path).exists()
    return found_path

@click.group()
def main():
    """Helper Views for Rasa NLU"""
    pass


@click.command()
@click.option('--port', default=8501, help='Port number, default=8501.')
def overview(port):
    """Gives an overview of all results generated by `rasa train`."""
    app = app_path("viewresults.py")
    click.echo(click.style(f'Starting up {app}', fg='green'))
    print(app)
    subprocess.run(["streamlit", "run", "--server.port", str(port), app])


@click.command()
@click.option('--port', default=8501, help='Port number, default=8501.')
def diet_explorer(port):
    """Allows you to explore the DIET settings."""
    app = app_path("html/diet")
    click.echo(click.style(f'Starting up {app}', fg='green'))
    subprocess.run(["python", "-m", "http.server", str(port), "--directory", app])


@click.command()
@click.argument('filename', type=click.Path(exists=True))
@click.argument('columns', nargs=-1)
@click.option('--port', default=8501, help='Port number, default=8501.')
def pcoords(filename, columns, port):
    """Parallel coordinates view of csv file *EXPERIMENTAL*."""
    df = pd.read_csv(filename)
    print("Warning: ignoring non-numeric columns for now.")
    if len(columns) == 0:
        print("Warning: no columns passed so I'll not do a subset.")
        columns = df.columns
    df = df[list(columns)].select_dtypes(include=['int64','float64'])
    for col in df.columns:
        if df[col].nunique() == 1:
            print(f"Warning: dropping {col} because it only has one value.")
            df = df.drop(col)
    print("Info: first few rows of dataframe")
    print(df.head())
    app = app_path("html/parallelcoords")
    df.to_csv(f"{app}/data.csv", index=False)
    click.echo(click.style(f'Starting up {app}', fg='green'))
    subprocess.run(["python", "-m", "http.server", str(port), "--directory", app])


main.add_command(overview)
main.add_command(diet_explorer)
main.add_command(pcoords)


if __name__ == "__main__":
    main()
