import pathlib
import subprocess

import click


def app_path(py_file):
    found_path = str(pathlib.Path(__file__).parent.absolute() / py_file)
    assert pathlib.Path(found_path).exists()
    return found_path

@click.group()
def main():
    """Helper Views for Rasa NLU"""
    pass


@click.command()
@click.option('--port', default=8501, help='Port number, default=8501.')
def overview(port):
    """Gives an overview of all results generated by `rasa train`."""
    app = app_path("viewresults.py")
    click.echo(click.style(f'Starting up {app}', fg='green'))
    print(app)
    subprocess.run(["streamlit", "run", "--server.port", str(port), app])


@click.command()
@click.option('--port', default=8501, help='Port number, default=8501.')
def diet_explorer(port):
    """Allows you to explore the DIET settings."""
    app = app_path("html/diet")
    click.echo(click.style(f'Starting up {app}', fg='green'))
    subprocess.run(["python", "-m", "http.server", str(port), "--directory", app])


main.add_command(overview)
main.add_command(diet_explorer)


if __name__ == "__main__":
    main()
